name = "ipgeek"
main = "workers/api.js"
compatibility_date = "2024-01-01"

[vars]
CACHE_TTL = "3600"

[[routes]]
pattern = "https://api.ipgeek.top/*"
zone_name = "ipgeek.top"

[pages_build_output_dir]
directory = "dist"
